### ISSUE TITLE
How to make the Iframe responsive?

### ISSUE THREAD

**Issue by josuablejeru** [tjallingt/react-youtube#242]
# Responsive Iframe
Hi first I want to thank you for your work, it has really an easy api to work with!

**Here my question:**
I had a really hard time try to make the iframe responsive on mobile and desktop. Did anyone have an Idea how we could implement a autoresize feature to this Component so you can make it responsive by a prop? 

(If it is not possible... can anyone give me a hint how to make my iframe responsive in a material-ui card?)

Thanks for your time!

**Comment by redshoga** [comment]
It could be implemented by using `containerClassName` props.

```css
.youtubeContainer {
  position: relative;
  width: 100%;
  height: 0;
  padding-bottom: 56.25%;
  overflow: hidden;
  margin-bottom: 50px;
}

.youtubeContainer iframe {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
}
```

```tsx
<YouTube videoId="2g811Eo7K8U" containerClassName={"youtubeContainer"} />
```
